name: Manual PCAP to JSON Converter

on:
  workflow_dispatch:
    inputs:
      pcap_url:
        description: "Paste the PCAP file URL"
        required: true

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y tshark
          pip install pyshark requests

      - name: Run PCAP to JSON Conversion
        run: python convert_pcap.py "${{ inputs.pcap_url }}" output.json

      - name: Upload JSON Output
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: converted-json
          path: output.json
